alter PROC [dbo].[USP_R_ITEMCODES]      
@CATEGORYID INT = 0                    
AS                        
BEGIN                        
                    
SELECT I.ITEMID, I.SKUCODE, I.ITEMNAME,C.CATEGORYNAME                    
FROM ITEM I LEFT JOIN TBLCATEGORY C ON I.CATEGORYID = C.CATEGORYID                    
WHERE I.DELETEDDATE IS NULL                        
                        
 SELECT                        
  IBC.ITEMCODEID,I.ITEMID,IBC.ITEMCODE,I.ITEMNAME,I.SKUCODE,                
  C.CATEGORYNAME,CU.FULLNAME AS CREATEDBY,I.CREATEDDATE,                
  UU.FULLNAME AS UPDATEDBY,I.UPDATEDATE,ISNULL(I.ISOPENITEM,0) AS ISOPENITEM,                
   ISNULL(I.PARENTITEMID,0) AS PARENTITEMID,UM.MULTIPLIER ,          
   I.CATEGORYID,C.CATEGORYNAME,I.SUBCATEGORYID,SC.SUBCATEGORYNAME,    
   IBC.HSNCODE    
 FROM                        
  ITEMCODE IBC                         
  INNER JOIN ITEM I ON I.ITEMID = IBC.ITEMID                        
  LEFT JOIN TBLUSER CU ON CU.USERID = I.CREATEDBY                        
  LEFT JOIN TBLUSER UU ON UU.USERID = I.UPDATEDBY                        
 LEFT JOIN TBLCATEGORY C ON I.CATEGORYID = C.CATEGORYID                    
 LEFT JOIN SUBCATEGORY sc ON I.SUBCATEGORYID = SC.SUBCATEGORYID    
 LEFT JOIN UOM UM ON I.UOMID = UM.UOMID                
 WHERE   IBC.DELETEDDATE IS NULL                        
              
 EXEC [USP_R_NONEANLIST]              
        
 IF(@CATEGORYID <> 10)        
 BEGIN        
        
 SELECT                        
  IBC.ITEMCODEID,I.ITEMID,IBC.ITEMCODE,I.ITEMNAME,I.SKUCODE,                
  C.CATEGORYNAME,CU.FULLNAME AS CREATEDBY,I.CREATEDDATE,                
  UU.FULLNAME AS UPDATEDBY,I.UPDATEDATE,ISNULL(I.ISOPENITEM,0) AS ISOPENITEM,                
   ISNULL(I.PARENTITEMID,0) AS PARENTITEMID,UM.MULTIPLIER ,          
   I.CATEGORYID,C.CATEGORYNAME,I.SUBCATEGORYID,SC.SUBCATEGORYNAME,    
   IBC.HSNCODE    
 FROM                       
  ITEMCODE IBC                         
  INNER JOIN ITEM I ON I.ITEMID = IBC.ITEMID                        
  LEFT JOIN TBLUSER CU ON CU.USERID = I.CREATEDBY                        
  LEFT JOIN TBLUSER UU ON UU.USERID = I.UPDATEDBY                        
 LEFT JOIN TBLCATEGORY C ON I.CATEGORYID = C.CATEGORYID                    
 LEFT JOIN SUBCATEGORY SC ON I.SUBCATEGORYID = SC.SUBCATEGORYID  
 LEFT JOIN UOM UM ON I.UOMID = UM.UOMID                
 WHERE  /*I.CATEGORYID = @CATEGORYID AND*/ IBC.DELETEDDATE IS NULL                   
        
 END        
              
END 
GO
ALTER PROC [dbo].[USP_R_ITEMVISUALIZER]        
@ItemID INT        
AS        
BEGIN        
        
 SELECT I.ITEMNAME, I.SKUCODE, I.DESCRIPTION        
 FROM ITEM I        
 WHERE I.ITEMID = @ItemID        
        
 SELECT         
  IC.ITEMCODEID        
  , IC.ITEMCODE        
  , IC.ISEAN        
  , IC.HSNCODE        
  , CU.FULLNAME AS CREATEDBY        
  , IC.CREATEDDATE        
  , UU.FULLNAME AS UPDATEDBY        
  , IC.UPDATEDATE        
 FROM         
  ITEMCODE IC        
  LEFT JOIN TBLUSER CU ON CU.USERID = IC.CREATEDBY        
  LEFT JOIN TBLUSER UU ON UU.USERID = IC.UPDATEDBY        
 WHERE IC.ITEMID = @ItemID        
        
 SELECT         
  IP.ITEMPRICEID        
  , IP.ITEMCODEID        
  , IC.ITEMCODE        
  , ICP.COSTPRICEWT        
  , ICP.COSTPRICEWOT        
  , IP.SALEPRICE        
  , IP.MRP        
  , IP.GSTID        
  , GST.GSTCODE        
  , CU.FULLNAME AS CREATEDBY        
  , IP.CREATEDDATE        
  , UU.FULLNAME AS UPDATEDBY        
  , IP.UPDATEDATE        
 FROM        
  ITEMPRICE IP        
  INNER JOIN ITEMCODE IC ON IC.ITEMCODEID = IP.ITEMCODEID        
  INNER JOIN GSTDETAIL GST ON GST.GSTID = IP.GSTID        
  INNER JOIN ITEMCOSTPRICE ICP ON ICP.ITEMPRICEID = IP.ITEMPRICEID      
  LEFT JOIN TBLUSER CU ON CU.USERID = IP.CREATEDBY        
  LEFT JOIN TBLUSER UU ON UU.USERID = IP.UPDATEDBY        
 WHERE IC.ITEMID = @ItemID        
        
 SELECT         
  SS.BRANCHID        
  , B.BRANCHNAME        
  , SS.QUANTITY        
  , SS.INTRANSITQUANTITY        
  , SS.WEIGHTINKGS        
  , SS.INTRANSITWEIGHTINKGS        
 FROM         
  STOCKSUMMARY SS        
  INNER JOIN BRANCH B ON B.BRANCHID = SS.BRANCHID
  INNER JOIN ITEMPRICE IP ON SS.ITEMPRICEID = IP.ITEMPRICEID
  INNER JOIN ITEMCODE IC ON IP.ITEMCODEID = IC.ITEMCODEID
  WHERE IC.ITEMID = @ItemID
 
        
END 
GO