USE [C:\Windows\NSRetailPOS\NSRETAILPOS.MDF]
GO
:ON ERROR EXIT
GO

/****** Object:  StoredProcedure [dbo].[POS_USP_CU_CREFUND]    Script Date: 11-08-2024 23:47:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[POS_USP_CU_CREFUND]  
@dtRefund POS_CREFUNDTYPE READONLY,  
@UserID int  
, @BillID INT
, @CustomerName VARCHAR(100)
, @CustomerPhone VARCHAR(10)
AS  
BEGIN  
  
INSERT INTO POS_CREFUND(BILLDETAILID,REFUNDQUANTITY,  
REFUNDWEIGHTINKGS,REFUNDAMOUNT,CREATEDBY,CREATEDDATE)  
SELECT BILLDETAILID,REFUNDQUANTITY,  
REFUNDWEIGHTINKGS,REFUNDAMOUNT,@UserID,GETDATE() FROM @dtRefund  
WHERE REFUNDQUANTITY > 0  
  

  UPDATE POS_BILL
  SET
	CUSTOMERNAME = @CustomerName
	, CUSTOMERNUMBER = @CustomerPhone
	, UPDATEDBY = @UserID
	, UPDATEDDATE = GETDATE()
  WHERE 
	BILLID = @BillID
	AND (ISNULL(CUSTOMERNAME, '') <> @CustomerName OR ISNULL(CUSTOMERNUMBER, '') <> @CustomerPhone)

END
GO


/****** Object:  StoredProcedure [dbo].[POS_USP_R_ITEMMRPLIST]    Script Date: 20-08-2024 16:57:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [dbo].[POS_USP_R_ITEMMRPLIST]  
@ItemCodeID INT 
, @FilterMRPByStock BIT = 0
AS  
BEGIN  

	--SELECT  
	--	IP.ITEMPRICEID, IP.MRP, IP.SALEPRICE, GST.GSTID, GST.GSTCODE, GST.SGST, GST.CGST, GST.IGST, GST.CESS  
	--	, CASE 
	--		WHEN 
	--			@FilterMRPByStock = 0 -- if filter is not enabled
	--			OR I.CATEGORYID = 16 -- if item is fruits
	--			OR I.CATEGORYID = 17 -- if item is vegetables
	--			OR IP.QTYORWEIGHTINKGS > 0 -- if stock exists
	--		THEN 'Yes' ELSE 'No' END AS ISSTOCKAVAILABLE
	--FROM
	--	(
	--		SELECT 
	--			ISNULL(CIP.ITEMPRICEID,PIP.ITEMPRICEID) AS ITEMPRICEID
	--		FROM POS_ITEMPRICE PIP
	--			LEFT JOIN POS_ITEMPRICE CIP ON PIP.ITEMPRICEID = CIP.PARENTITEMPRICEID AND CIP.DELETEDDATE IS NULL
	--		WHERE PIP.ITEMCODEID = @ItemCodeID AND PIP.DELETEDDATE IS NULL 
	--		AND PIP.BRANCHID IS NULL
	--	) IPOUTER
	--	INNER JOIN POS_ITEMPRICE IP ON IPOUTER.ITEMPRICEID = IP.ITEMPRICEID
	--	INNER JOIN POS_ITEMCODE IC ON IC.ITEMCODEID = IP.ITEMCODEID
	--	INNER JOIN POS_ITEM I ON I.ITEMID = IC.ITEMID
	--	INNER JOIN POS_GSTDETAIL GST ON GST.GSTID = IP.GSTID  
	----WHERE
	----	(@FilterMRPByStock = 0 OR IP.QTYORWEIGHTINKGS > 0)
	--ORDER BY IP.ITEMPRICEID DESC

	SELECT  
		IP.ITEMPRICEID, IP.MRP, IP.SALEPRICE, GST.GSTID, GST.GSTCODE, GST.SGST, GST.CGST, GST.IGST, GST.CESS  
		, CASE 
			WHEN 
				@FilterMRPByStock = 0 -- if filter is not enabled
				OR I.CATEGORYID = 16 -- if item is fruits
				OR I.CATEGORYID = 17 -- if item is vegetables
				OR ISNULL(PIP.QTYORWEIGHTINKGS, IP.QTYORWEIGHTINKGS) > 0 -- if stock exists
			THEN 'Yes' ELSE 'No' END AS ISSTOCKAVAILABLE
	FROM
		POS_ITEMPRICE IP
		INNER JOIN POS_ITEMCODE IC ON IC.ITEMCODEID = IP.ITEMCODEID
		INNER JOIN POS_ITEM I ON I.ITEMID = IC.ITEMID
		INNER JOIN POS_GSTDETAIL GST ON GST.GSTID = IP.GSTID  
		LEFT JOIN POS_ITEMPRICE PIP ON PIP.ITEMPRICEID = IP.PARENTITEMPRICEID
	WHERE 
		IP.ITEMCODEID = @ItemCodeID 
		AND IP.DELETEDDATE IS NULL 
		AND PIP.DELETEDDATE IS NULL
	ORDER BY IP.ITEMPRICEID DESC

END
GO

UPDATE TBLCONFIG SET CONFIGVALUE = '1.6.2' WHERE CONFIGID = 1
GO