UPDATE ENTITYSYNCORDER SET SYNCORDER = 4 WHERE ENTITYID = 11 AND LOCATIONTYPE = 'Warehouse' AND SYNCDIRECTION = 'FromCloud'
GO
UPDATE ENTITYSYNCORDER SET SYNCORDER = 3 WHERE ENTITYID = 12 AND LOCATIONTYPE = 'Warehouse' AND SYNCDIRECTION = 'FromCloud'
GO