USE [NSRetail]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('[dbo].[ITEM_LOG]', 'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ITEM_LOG](
        [ITEMLOGID] [bigint] IDENTITY(1,1) NOT NULL,
        [ACTIONTYPE] [varchar](10) NOT NULL,
        [ACTIONDATE] [datetime] NOT NULL CONSTRAINT [DF_ITEM_LOG_ACTIONDATE] DEFAULT (GETDATE()),
        [ACTIONBY] [int] NULL,
        [CHANGEDCOLUMNS] [varchar](1000) NULL,
        [ITEMID] [int] NOT NULL,
        [SKUCODE] [varchar](10) NOT NULL,
        [ITEMNAME] [varchar](100) NOT NULL,
        [DESCRIPTION] [varchar](500) NULL,
        [CREATEDBY] [int] NULL,
        [CREATEDDATE] [datetime] NULL,
        [UPDATEDBY] [int] NULL,
        [UPDATEDATE] [datetime] NULL,
        [DELETEDBY] [int] NULL,
        [DELETEDDATE] [datetime] NULL,
        [CATEGORYID] [int] NULL,
        [SUBCATEGORYID] [int] NULL,
        [ISOPENITEM] [bit] NULL,
        [PARENTITEMID] [int] NULL,
        [UOMID] [int] NULL,
        [CLASSIFICATIONID] [int] NULL,
        [SUBCLASSIFICATIONID] [int] NULL,
        [BRANDID] [int] NULL,
        [MANUFACTURERID] [int] NULL,
        [UQCID] [int] NULL,
        [HSNCODE] [varchar](10) NULL,
        [GSTID] [int] NULL,
        [VENDORSKUCODE] [varchar](20) NULL,
        [SEASONALITYIDS] [varchar](500) NULL,
        [REFUNDPATHID] [int] NULL,
        [ISDSD] [bit] NULL,
        [INNERCASEQTY] [int] NULL,
        [OUTERCASEQTY] [int] NULL,
        [PRODUCTRANK] [decimal](18, 2) NULL,
        [SUPPLIERINDENTITEMTYPEID] [int] NULL,
        CONSTRAINT [PK_ITEM_LOG] PRIMARY KEY CLUSTERED ([ITEMLOGID] ASC)
    )
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [name] = 'IX_ITEM_LOG_ITEMID_ACTIONDATE' AND [object_id] = OBJECT_ID('[dbo].[ITEM_LOG]'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ITEM_LOG_ITEMID_ACTIONDATE]
    ON [dbo].[ITEM_LOG] ([ITEMID] ASC, [ACTIONDATE] DESC, [ITEMLOGID] DESC)
END
GO

CREATE OR ALTER TRIGGER [dbo].[TRG_ITEM_AUDIT]
ON [dbo].[ITEM]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @SessionUserID int = TRY_CONVERT(int, SESSION_CONTEXT(N'UserID'));

    IF EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
    BEGIN
        INSERT INTO [dbo].[ITEM_LOG] (
            [ACTIONTYPE], [ACTIONBY], [CHANGEDCOLUMNS], [ITEMID], [SKUCODE], [ITEMNAME], [DESCRIPTION],
            [CREATEDBY], [CREATEDDATE], [UPDATEDBY], [UPDATEDATE], [DELETEDBY], [DELETEDDATE],
            [CATEGORYID], [SUBCATEGORYID], [ISOPENITEM], [PARENTITEMID], [UOMID], [CLASSIFICATIONID],
            [SUBCLASSIFICATIONID], [BRANDID], [MANUFACTURERID], [UQCID], [HSNCODE], [GSTID],
            [VENDORSKUCODE], [SEASONALITYIDS], [REFUNDPATHID], [ISDSD], [INNERCASEQTY], [OUTERCASEQTY],
            [PRODUCTRANK], [SUPPLIERINDENTITEMTYPEID])
        SELECT
            'INSERT', COALESCE(@SessionUserID, i.[CREATEDBY]), 'ALL', i.[ITEMID], i.[SKUCODE], i.[ITEMNAME], i.[DESCRIPTION],
            i.[CREATEDBY], i.[CREATEDDATE], i.[UPDATEDBY], i.[UPDATEDATE], i.[DELETEDBY], i.[DELETEDDATE],
            i.[CATEGORYID], i.[SUBCATEGORYID], i.[ISOPENITEM], i.[PARENTITEMID], i.[UOMID], i.[CLASSIFICATIONID],
            i.[SUBCLASSIFICATIONID], i.[BRANDID], i.[MANUFACTURERID], i.[UQCID], i.[HSNCODE], i.[GSTID],
            i.[VENDORSKUCODE], i.[SEASONALITYIDS], i.[REFUNDPATHID], i.[ISDSD], i.[INNERCASEQTY], i.[OUTERCASEQTY],
            i.[PRODUCTRANK], i.[SUPPLIERINDENTITEMTYPEID]
        FROM inserted i;
    END
    ELSE IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN
        INSERT INTO [dbo].[ITEM_LOG] (
            [ACTIONTYPE], [ACTIONBY], [CHANGEDCOLUMNS], [ITEMID], [SKUCODE], [ITEMNAME], [DESCRIPTION],
            [CREATEDBY], [CREATEDDATE], [UPDATEDBY], [UPDATEDATE], [DELETEDBY], [DELETEDDATE],
            [CATEGORYID], [SUBCATEGORYID], [ISOPENITEM], [PARENTITEMID], [UOMID], [CLASSIFICATIONID],
            [SUBCLASSIFICATIONID], [BRANDID], [MANUFACTURERID], [UQCID], [HSNCODE], [GSTID],
            [VENDORSKUCODE], [SEASONALITYIDS], [REFUNDPATHID], [ISDSD], [INNERCASEQTY], [OUTERCASEQTY],
            [PRODUCTRANK], [SUPPLIERINDENTITEMTYPEID])
        SELECT
            CASE WHEN i.[DELETEDDATE] IS NOT NULL AND d.[DELETEDDATE] IS NULL THEN 'DELETE' ELSE 'UPDATE' END,
            COALESCE(@SessionUserID, i.[UPDATEDBY], i.[DELETEDBY]),
            NULLIF(STUFF(CONCAT(
                CASE WHEN EXISTS (SELECT i.[SKUCODE] EXCEPT SELECT d.[SKUCODE]) THEN ', SKUCODE' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[ITEMNAME] EXCEPT SELECT d.[ITEMNAME]) THEN ', ITEMNAME' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[DESCRIPTION] EXCEPT SELECT d.[DESCRIPTION]) THEN ', DESCRIPTION' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[CREATEDBY] EXCEPT SELECT d.[CREATEDBY]) THEN ', CREATEDBY' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[CREATEDDATE] EXCEPT SELECT d.[CREATEDDATE]) THEN ', CREATEDDATE' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[UPDATEDBY] EXCEPT SELECT d.[UPDATEDBY]) THEN ', UPDATEDBY' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[UPDATEDATE] EXCEPT SELECT d.[UPDATEDATE]) THEN ', UPDATEDATE' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[DELETEDBY] EXCEPT SELECT d.[DELETEDBY]) THEN ', DELETEDBY' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[DELETEDDATE] EXCEPT SELECT d.[DELETEDDATE]) THEN ', DELETEDDATE' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[CATEGORYID] EXCEPT SELECT d.[CATEGORYID]) THEN ', CATEGORYID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[SUBCATEGORYID] EXCEPT SELECT d.[SUBCATEGORYID]) THEN ', SUBCATEGORYID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[ISOPENITEM] EXCEPT SELECT d.[ISOPENITEM]) THEN ', ISOPENITEM' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[PARENTITEMID] EXCEPT SELECT d.[PARENTITEMID]) THEN ', PARENTITEMID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[UOMID] EXCEPT SELECT d.[UOMID]) THEN ', UOMID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[CLASSIFICATIONID] EXCEPT SELECT d.[CLASSIFICATIONID]) THEN ', CLASSIFICATIONID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[SUBCLASSIFICATIONID] EXCEPT SELECT d.[SUBCLASSIFICATIONID]) THEN ', SUBCLASSIFICATIONID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[BRANDID] EXCEPT SELECT d.[BRANDID]) THEN ', BRANDID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[MANUFACTURERID] EXCEPT SELECT d.[MANUFACTURERID]) THEN ', MANUFACTURERID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[UQCID] EXCEPT SELECT d.[UQCID]) THEN ', UQCID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[HSNCODE] EXCEPT SELECT d.[HSNCODE]) THEN ', HSNCODE' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[GSTID] EXCEPT SELECT d.[GSTID]) THEN ', GSTID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[VENDORSKUCODE] EXCEPT SELECT d.[VENDORSKUCODE]) THEN ', VENDORSKUCODE' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[SEASONALITYIDS] EXCEPT SELECT d.[SEASONALITYIDS]) THEN ', SEASONALITYIDS' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[REFUNDPATHID] EXCEPT SELECT d.[REFUNDPATHID]) THEN ', REFUNDPATHID' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[ISDSD] EXCEPT SELECT d.[ISDSD]) THEN ', ISDSD' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[INNERCASEQTY] EXCEPT SELECT d.[INNERCASEQTY]) THEN ', INNERCASEQTY' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[OUTERCASEQTY] EXCEPT SELECT d.[OUTERCASEQTY]) THEN ', OUTERCASEQTY' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[PRODUCTRANK] EXCEPT SELECT d.[PRODUCTRANK]) THEN ', PRODUCTRANK' ELSE '' END,
                CASE WHEN EXISTS (SELECT i.[SUPPLIERINDENTITEMTYPEID] EXCEPT SELECT d.[SUPPLIERINDENTITEMTYPEID]) THEN ', SUPPLIERINDENTITEMTYPEID' ELSE '' END
            ), 1, 2, ''), ''),
            i.[ITEMID], i.[SKUCODE], i.[ITEMNAME], i.[DESCRIPTION],
            i.[CREATEDBY], i.[CREATEDDATE], i.[UPDATEDBY], i.[UPDATEDATE], i.[DELETEDBY], i.[DELETEDDATE],
            i.[CATEGORYID], i.[SUBCATEGORYID], i.[ISOPENITEM], i.[PARENTITEMID], i.[UOMID], i.[CLASSIFICATIONID],
            i.[SUBCLASSIFICATIONID], i.[BRANDID], i.[MANUFACTURERID], i.[UQCID], i.[HSNCODE], i.[GSTID],
            i.[VENDORSKUCODE], i.[SEASONALITYIDS], i.[REFUNDPATHID], i.[ISDSD], i.[INNERCASEQTY], i.[OUTERCASEQTY],
            i.[PRODUCTRANK], i.[SUPPLIERINDENTITEMTYPEID]
        FROM inserted i
        INNER JOIN deleted d ON d.[ITEMID] = i.[ITEMID];
    END
    ELSE IF NOT EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN
        INSERT INTO [dbo].[ITEM_LOG] (
            [ACTIONTYPE], [ACTIONBY], [CHANGEDCOLUMNS], [ITEMID], [SKUCODE], [ITEMNAME], [DESCRIPTION],
            [CREATEDBY], [CREATEDDATE], [UPDATEDBY], [UPDATEDATE], [DELETEDBY], [DELETEDDATE],
            [CATEGORYID], [SUBCATEGORYID], [ISOPENITEM], [PARENTITEMID], [UOMID], [CLASSIFICATIONID],
            [SUBCLASSIFICATIONID], [BRANDID], [MANUFACTURERID], [UQCID], [HSNCODE], [GSTID],
            [VENDORSKUCODE], [SEASONALITYIDS], [REFUNDPATHID], [ISDSD], [INNERCASEQTY], [OUTERCASEQTY],
            [PRODUCTRANK], [SUPPLIERINDENTITEMTYPEID])
        SELECT
            'DELETE', COALESCE(@SessionUserID, d.[DELETEDBY], d.[UPDATEDBY]), 'ALL', d.[ITEMID], d.[SKUCODE], d.[ITEMNAME], d.[DESCRIPTION],
            d.[CREATEDBY], d.[CREATEDDATE], d.[UPDATEDBY], d.[UPDATEDATE], d.[DELETEDBY], d.[DELETEDDATE],
            d.[CATEGORYID], d.[SUBCATEGORYID], d.[ISOPENITEM], d.[PARENTITEMID], d.[UOMID], d.[CLASSIFICATIONID],
            d.[SUBCLASSIFICATIONID], d.[BRANDID], d.[MANUFACTURERID], d.[UQCID], d.[HSNCODE], d.[GSTID],
            d.[VENDORSKUCODE], d.[SEASONALITYIDS], d.[REFUNDPATHID], d.[ISDSD], d.[INNERCASEQTY], d.[OUTERCASEQTY],
            d.[PRODUCTRANK], d.[SUPPLIERINDENTITEMTYPEID]
        FROM deleted d;
    END
END
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_R_ITEMHISTORY]
(
    @ITEMID int
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        il.[ITEMLOGID],
        il.[ACTIONTYPE] AS [Action],
        il.[ACTIONDATE] AS [Action Date],
        il.[ACTIONBY],
        COALESCE(u.[FULLNAME], u.[USERNAME], CONVERT(varchar(20), il.[ACTIONBY])) AS [Action By],
        il.[CHANGEDCOLUMNS] AS [Changed Columns],
        il.[ITEMID],
        il.[SKUCODE],
        il.[ITEMNAME],
        il.[DESCRIPTION],
        il.[CATEGORYID],
        c.[CATEGORYNAME],
        il.[SUBCATEGORYID],
        sc.[SUBCATEGORYNAME],
        il.[ISOPENITEM],
        il.[PARENTITEMID],
        pi.[SKUCODE] AS [PARENTSKUCODE],
        pi.[ITEMNAME] AS [PARENTITEMNAME],
        il.[UOMID],
        uom.[DISPLAYVALUE] AS [UOM],
        il.[CLASSIFICATIONID],
        ic.[CLASSIFICATIONNAME],
        il.[SUBCLASSIFICATIONID],
        isc.[SUBCLASSIFICATIONNAME],
        il.[BRANDID],
        b.[BRANDNAME],
        il.[MANUFACTURERID],
        m.[MANUFACTURERNAME],
        il.[UQCID],
        uqc.[UQCNAME],
        il.[HSNCODE],
        il.[GSTID],
        g.[GSTCODE],
        il.[VENDORSKUCODE],
        il.[SEASONALITYIDS],
        il.[REFUNDPATHID],
        rp.[REFUNDPATHTEXT],
        il.[ISDSD],
        il.[INNERCASEQTY],
        il.[OUTERCASEQTY],
        il.[PRODUCTRANK],
        il.[SUPPLIERINDENTITEMTYPEID],
        siit.[ENUMVALUE] AS [SUPPLIERINDENTITEMTYPE],
        il.[CREATEDBY],
        il.[CREATEDDATE],
        il.[UPDATEDBY],
        il.[UPDATEDATE],
        il.[DELETEDBY],
        il.[DELETEDDATE]
    FROM [dbo].[ITEM_LOG] il
    LEFT JOIN [dbo].[TBLUSER] u ON u.[USERID] = il.[ACTIONBY]
    LEFT JOIN [dbo].[TBLCATEGORY] c ON c.[CATEGORYID] = il.[CATEGORYID]
    LEFT JOIN [dbo].[SUBCATEGORY] sc ON sc.[SUBCATEGORYID] = il.[SUBCATEGORYID]
    LEFT JOIN [dbo].[ITEM] pi ON pi.[ITEMID] = il.[PARENTITEMID]
    LEFT JOIN [dbo].[UOM] uom ON uom.[UOMID] = il.[UOMID]
    LEFT JOIN [dbo].[ITEMCLASSIFICATION] ic ON ic.[CLASSIFICATIONID] = il.[CLASSIFICATIONID]
    LEFT JOIN [dbo].[ITEMSUBCLASSIFICATION] isc ON isc.[SUBCLASSIFICATIONID] = il.[SUBCLASSIFICATIONID]
    LEFT JOIN [dbo].[TBLBRAND] b ON b.[BRANDID] = il.[BRANDID]
    LEFT JOIN [dbo].[TBLMANUFACTURER] m ON m.[MANUFACTURERID] = il.[MANUFACTURERID]
    LEFT JOIN [dbo].[UQCDATA] uqc ON uqc.[UQCID] = il.[UQCID]
    LEFT JOIN [dbo].[GSTDETAIL] g ON g.[GSTID] = il.[GSTID]
    LEFT JOIN [dbo].[REFUNDPATH] rp ON rp.[REFUNDPATHID] = il.[REFUNDPATHID]
    LEFT JOIN [dbo].[TBLENUM] siit ON siit.[ENUMID] = il.[SUPPLIERINDENTITEMTYPEID]
        AND siit.[ENUMTYPE] = 'Supplier Indent Item Type'
    WHERE il.[ITEMID] = @ITEMID
    ORDER BY il.[ACTIONDATE] DESC, il.[ITEMLOGID] DESC;
END
GO
