SELECT distinct * FROM ITEMCOSTPRICE
SELECT * FROM skumaster

INSERT INTO ITEMCOSTPRICE(ITEMPRICEID, COSTPRICEWT, GSTID, CREATEDBY, CREATEDDATE)
SELECT IP.ITEMPRICEID, SKUIP.Cost_Price, SKUIP.GSTID, 4, GETDATE() FROM
	(Select distinct Product_ID, EAN_Code, Sale_Price, MRP, 
	CASE Tax_Code
	 WHEN 'GST_0'	 THEN	 6
	 WHEN 'GST_12'	 THEN	5
	 WHEN 'GST_18'	 THEN	8
	 WHEN 'GST_28'	 THEN	9
	 WHEN 'GST_28_12' THEN	11
	 WHEN 'GST_28_36' THEN	 12
	 WHEN 'GST_28_5'	 THEN	10
	 WHEN 'GST_3'	 THEN	7
	 WHEN 'GST_5'	 THEN	4
	END AS GSTID, Cost_Price
	from skumaster) SKUIP
INNER JOIN ITEM I ON I.SKUCODE = SKUIP.Product_ID
INNER JOIN ITEMCODE IC ON IC.ITEMCODE = SKUIP.EAN_Code AND IC.ITEMID = I.ITEMID
INNER JOIN ITEMPRICE IP ON IP.ITEMCODEID = IC.ITEMCODEID AND SKUIP.Sale_Price = IP.SALEPRICE AND SKUIP.MRP = IP.MRP
WHERE
	SKUIP.GSTID IS NOT NULL

UPDATE ICP
SET ICP.COSTPRICEWOT = ICP.COSTPRICEWT - ((ICP.COSTPRICEWT * (CGST + SGST + IGST + CESS)) / 100)
FROM 
	ITEMCOSTPRICE ICP
	INNER JOIN GSTDETAIL GST ON GST.GSTID = ICP.GSTID

SELECT CGST + SGST + IGST + CESS FROM GSTDETAIL