SELECT * FROM ITEMPRICE

INSERT INTO ITEMPRICE(ITEMCODEID, SALEPRICE, MRP, GSTID, CREATEDBY, CREATEDDATE)
SELECT DISTINCT IC.ITEMCODEID, SKUIP.Sale_Price, SKUIP.MRP, SKUIP.GSTID, 4, GETDATE() FROM
	(Select Product_ID, EAN_Code, Sale_Price, MRP, 
	CASE Tax_Code
	 WHEN 'GST_0'	 THEN	 6
	 WHEN 'GST_12'	 THEN	5
	 WHEN 'GST_18'	 THEN	8
	 WHEN 'GST_28'	 THEN	9
	 WHEN 'GST_28_12' THEN	11
	 WHEN 'GST_28_36' THEN	 12
	 WHEN 'GST_28_5'	 THEN	10
	 WHEN 'GST_3'	 THEN	7
	 WHEN 'GST_5'	 THEN	4
	END AS GSTID
	from skumaster) SKUIP
INNER JOIN ITEM I ON I.SKUCODE = SKUIP.Product_ID
INNER JOIN ITEMCODE IC ON IC.ITEMCODE = SKUIP.EAN_Code AND IC.ITEMID = I.ITEMID
WHERE
	SKUIP.GSTID IS NOT NULL


select distinct Tax_Code from skumaster where Tax_Code like 'GST%' order by 1
select * from GSTDETAIL


select DISTINCT ITEMCODEID, SALEPRICE, MRP, GSTID, CREATEDBY, CREATEDDATE from ITEMPRICE
--DELETE FROM ITEMPRICE
