
INSERT INTO ITEMCODE(ITEMID, ITEMCODE, ISEAN, HSNCODE, CREATEDBY, CREATEDDATE)
SELECT I.ITEMID, SKUIC.EAN_Code, SKUIC.ISEAN, SKUIC.HSN_Code, SKUIC.CREATEDBY, SKUIC.CREATEDDATE
FROM
(SELECt DISTINCT 
	Product_ID
	, EAN_Code
	, HSN_Code
	, CASE 
		WHEN Product_ID = EAN_Code OR '00' + Product_ID = EAN_Code THEN 0
		ELSE 1 END AS ISEAN
	, 4 AS CREATEDBY, GETDATE() AS CREATEDDATE
	FROM skumaster where Product_ID is not null) SKUIC
INNER JOIN ITEM I ON I.SKUCODE = SKUIC.Product_ID

	
