select * from STOCKSUMMARY
INSERT INTO STOCKSUMMARY(BRANCHID
, ITEMPRICEID
, QUANTITY
, INTRANSITQUANTITY
, WEIGHTINKGS
, INTRANSITWEIGHTINKGS)
SELECT  BRANCHID, ITEMPRICEID, 0, 0, 0, 0
FROM ITEMPRICE CROSS APPLY BRANCH