using DataAccess;
using DevExpress.XtraEditors;
using Entity;
using NSRetail.Supplier;
using System;
using System.Collections.Generic;
using System.Data;
using System.Windows.Forms;

namespace NSRetail.ReportForms.Supplier.SupplierReports
{
    public partial class ucSupplierReturnsList : SearchCriteriaBase
    {   
        public ucSupplierReturnsList()
        {
            InitializeComponent();
            Dictionary<string, string> columnHeaders = new Dictionary<string, string>
            {
                { "SUPPLIERRETURNSID", "Supplier ReturnsID" }
                , { "SUPPLIERID", "Supplier ID" }
                , { "DEALERNAME", "Supplier" }
                , { "PROPOSEDVALUE", "DN Value" }
                , { "ACCEPTEDVALUE", "CN Value" }
                , { "REJECTEDVALUE", "Pending Value" }
                , { "CREATEDBY", "Created By" }
                , { "CREATEDDATE", "Created Date" }
                , { "CNINITIATEDBY", "Generated By" }
                , { "CNINITIATEDDATE", "Generated Date" }
                , { "UPDATEDBY", "Closed By" }
                , { "UPDATEDDATE", "Closed Date" }
                , { "STATUS", "Status" }
            };

            ContextmenuItems = new Dictionary<string, string>
            { 
                { "Print", "9B101F20-1E08-44A0-BE65-A8FA5D197574" },
                { "Map Credit Note", "00D6561B-C2D3-4D6C-A88A-BC14B519925F" },
                { "Discard", "8F3C9A6E-4C21-4F3D-B6E2-9C7A4B1D5F92" }
            };

            cmbSupplier.Properties.DataSource = new MasterRepository().GetDealer(true);
            cmbSupplier.Properties.ValueMember = "DEALERID";
            cmbSupplier.Properties.DisplayMember = "DEALERNAME";
            cmbSupplier.EditValue = 0;
            dtpFromDate.EditValue = DateTime.Now.AddDays(-7);
            dtpToDate.EditValue = DateTime.Now;

            SetFocusControls(cmbSupplier, dtpToDate, columnHeaders);
        }

        public override object GetData()
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>
            {
                { "SupplierID",  cmbSupplier.EditValue }
                ,{ "FromDate",  dtpFromDate.EditValue }
                ,{ "ToDate", dtpToDate.EditValue }
                ,{ "CategoryID", Utility.CategoryID}
            };
            return GetReportData("USP_R_SUPPLIERRETURNS", parameters);
        }

        public override void ActionExecute(string buttonText, DataRow drFocusedRow)
        {
            switch (buttonText)
            {
                case "Map Credit Note":
                    DataTable dt = new SupplierRepository().GetSupplierReturnsforCN(drFocusedRow["SUPPLIERRETURNSID"]);
                        
                    frmViewReturnItems obj = 
                        new frmViewReturnItems(dt, 
                            drFocusedRow["DEALERNAME"], 
                            drFocusedRow["SUPPLIERRETURNSID"],
                            drFocusedRow["STATUS"].Equals("Open") || drFocusedRow["STATUS"].Equals("Partially Closed"));

                    obj.ShowInTaskbar = false;
                    obj.StartPosition = FormStartPosition.CenterScreen;
                    obj.IconOptions.ShowIcon = false;
                    obj.ShowDialog();
                    (ParentForm as frmReportPlaceHolder)?.btnSearch_Click(null, null);
                    break;
                case "Print":
                    if(drFocusedRow["STATUS"].Equals("Draft"))
                    {
                        MessageBox.Show("Cannot print debit note for Draft status.", "NS Retail", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        return;
                    }
                    SupplierHelper.ShowSupplierDebitNote(drFocusedRow["SUPPLIERRETURNSID"]);
                    break;
                case "Discard":
                    if (drFocusedRow["STATUS"].Equals("Partially Closed") || drFocusedRow["STATUS"].Equals("Closed"))
                    {
                        MessageBox.Show("Cannot discard debit note which closed.", "NS Retail", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        return;
                    }
                    try
                    {
                        if (drFocusedRow["SUPPLIERRETURNSID"] == null || drFocusedRow["SUPPLIERRETURNSID"].Equals(0))
                        {
                            var result = XtraMessageBox.Show("Are sure want to discard return sheet?",
                                "Confirmation!",
                                MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                            if (!Convert.ToString(result).ToLower().Equals("yes"))
                                return;
                            new SupplierRepository().DiscardSupplierReturns(drFocusedRow["SUPPLIERRETURNSID"], Utility.UserID);
                            XtraMessageBox.Show("Return sheet discarded successfully.", "Information!", MessageBoxButtons.OK, MessageBoxIcon.Information);
                            (ParentForm as frmReportPlaceHolder)?.btnSearch_Click(null, null);
                        }
                    }
                    catch (Exception ex)
                    {
                        ErrorManagement.ErrorMgmt.ShowError(ex);
                    }
                    break;
            }
        }
    }
}
