using DataAccess;
using DevExpress.XtraEditors;
using Entity;
using NSRetail.Supplier;
using System;
using System.Collections.Generic;
using System.Data;
using System.Windows.Forms;

namespace NSRetail.ReportForms.Supplier.SupplierReports
{
    public partial class ucSupplierReturnsList : SearchCriteriaBase
    {   
        public ucSupplierReturnsList()
        {
            InitializeComponent();
            Dictionary<string, string> columnHeaders = new Dictionary<string, string>
            {
                { "SUPPLIERRETURNSID", "Supplier ReturnsID" }
                , { "SUPPLIERID", "Supplier ID" }
                , { "DEALERNAME", "Supplier" }
                , { "PROPOSEDVALUE", "DN Value" }
                , { "ACCEPTEDVALUE", "CN Value" }
                , { "REJECTEDVALUE", "Pending Value" }
                , { "CREATEDBY", "Created By" }
                , { "CREATEDDATE", "Created Date" }
                , { "CNINITIATEDBY", "Generated By" }
                , { "CNINITIATEDDATE", "Generated Date" }
                , { "UPDATEDBY", "Closed By" }
                , { "UPDATEDDATE", "Closed Date" }
                , { "STATUS", "Status" }
            };

            ContextmenuItems = new Dictionary<string, string>
            {
                { "View Items", "F6A1E4C7-8B23-4F9D-A2C1-9E7B5D6A3F10" },
                { "Map Credit Note", "00D6561B-C2D3-4D6C-A88A-BC14B519925F" },
                { "View Credit Note Mapping", "6F3C2D9A-8B4E-4C6F-A1D9-2F7C9B3E4A12" },
                { "Print Purchase Return", "9B101F20-1E08-44A0-BE65-A8FA5D197574" },
                { "Print Damage Expiry", "C4A8F6E2-1B9D-4A3F-9C7E-6D2B5A8F0E41" },
                { "Discard", "8F3C9A6E-4C21-4F3D-B6E2-9C7A4B1D5F92" }
            };

            cmbSupplier.Properties.DataSource = new MasterRepository().GetDealer(true);
            cmbSupplier.Properties.ValueMember = "DEALERID";
            cmbSupplier.Properties.DisplayMember = "DEALERNAME";
            cmbSupplier.EditValue = 0;
            dtpFromDate.EditValue = DateTime.Now.AddDays(-7);
            dtpToDate.EditValue = DateTime.Now;

            SetFocusControls(cmbSupplier, dtpToDate, columnHeaders);
        }

        public override object GetData()
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>
            {
                { "SupplierID",  cmbSupplier.EditValue }
                ,{ "FromDate",  dtpFromDate.EditValue }
                ,{ "ToDate", dtpToDate.EditValue }
                ,{ "CategoryID", Utility.CategoryID}
            };
            return GetReportData("USP_R_SUPPLIERRETURNS", parameters);
        }

        public override void ActionExecute(string buttonText, DataRow dr)
        {
            if (dr == null) return;

            var id = dr["SUPPLIERRETURNSID"];
            var status = dr["STATUS"]?.ToString();
            var dealerName = dr["DEALERNAME"]?.ToString();
            var acceptedValue = dr["ACCEPTEDVALUE"];

            switch (buttonText)
            {
                case "View Items":
                    ViewItems(id, dealerName, status, acceptedValue);
                    break;

                case "Map Credit Note":
                    if (IsWriteOff(status, "Cannot map credit notes to write off debit note."))
                        return;

                    MapCreditNote(id, dealerName);
                    break;

                case "Print Purchase Return":
                    if (ValidatePrint(status)) return;
                    SupplierHelper.ShowSupplierDebitNote(id, true);
                    break;

                case "Print Damage Expiry":
                    if (ValidatePrint(status)) return;
                    SupplierHelper.ShowSupplierDebitNote(id, false);
                    break;

                case "View Credit Note Mapping":
                    if (IsWriteOff(status, "Cannot view credit note mappings of write off debit note."))
                        return;

                    ViewCreditNoteMapping(id);
                    break;

                case "Discard":
                    DiscardReturn(dr, id, status);
                    break;
            }
        }
        private void ViewItems(object id, string dealerName, string status, object acceptedValue)
        {
            var dt = new SupplierRepository().GetSupplierReturnsforCN(id);

            var form = new frmViewReturnItems(dt, dealerName, id, status, acceptedValue)
            {
                ShowInTaskbar = false,
                StartPosition = FormStartPosition.CenterScreen
            };

            form.IconOptions.ShowIcon = false;
            form.ShowDialog();

            RefreshParent();
        }
        private void MapCreditNote(object id, string dealerName)
        {
            var frm = new frmMapCreditNote(id, "SR", dealerName)
            {
                StartPosition = FormStartPosition.CenterParent
            };

            frm.ShowDialog();
            RefreshParent();
        }
        private void ViewCreditNoteMapping(object id)
        {
            var dt = new CreditNoteRepository().GetMappedCreditNotes(id, "SR");

            var frm = new frmViewCreditNoteMapping(dt, "SR")
            {
                ShowInTaskbar = false,
                StartPosition = FormStartPosition.CenterScreen
            };

            frm.IconOptions.ShowIcon = false;
            frm.ShowDialog();
        }
        private void DiscardReturn(DataRow dr, object id, string status)
        {
            if (status == "Partially Closed" || status == "Closed" || status == "Write Off")
            {
                ShowInfo("Cannot discard debit note which closed or write off.");
                return;
            }

            if (id == null || id.Equals(0)) return;

            var result = XtraMessageBox.Show(
                "Are sure want to discard return sheet?",
                "Confirmation!",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Question);

            if (result != DialogResult.Yes) return;

            try
            {
                new SupplierRepository().DiscardSupplierReturns(id, Utility.UserID);
                ShowInfo("Return sheet discarded successfully.");
                RefreshParent();
            }
            catch (Exception ex)
            {
                ErrorManagement.ErrorMgmt.ShowError(ex);
            }
        }
        private bool IsWriteOff(string status, string message)
        {
            if (status == "Write Off")
            {
                ShowInfo(message);
                return true;
            }
            return false;
        }

        private bool ValidatePrint(string status)
        {
            if (status == "Write Off")
            {
                ShowInfo("Cannot print of write off debit note.");
                return true;
            }

            if (status == "Draft")
            {
                ShowInfo("Cannot print for Draft status.");
                return true;
            }

            return false;
        }

        private void ShowInfo(string message)
        {
            XtraMessageBox.Show(message, "NS Retail", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void RefreshParent()
        {
            (ParentForm as frmReportPlaceHolder)?.btnSearch_Click(null, null);
        }
    }
}
