ALTER TABLE POS_BILL
ADD CUSTOMERGST VARCHAR(100) NULL
GO
DROP PROC [dbo].[USP_CU_POS_BILL]  
GO
/****** Object:  UserDefinedTableType [dbo].[POS_BILLTYPE]    Script Date: 15-11-2022 15:48:46 ******/
DROP TYPE [dbo].[POS_BILLTYPE]
GO

/****** Object:  UserDefinedTableType [dbo].[POS_BILLTYPE]    Script Date: 15-11-2022 15:48:46 ******/
CREATE TYPE [dbo].[POS_BILLTYPE] AS TABLE(
	[BILLID] [int] NOT NULL,
	[BRANCHCOUNTERID] [int] NOT NULL,
	[BILLNUMBER] [varchar](30) NULL,
	[CREATEDBY] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[UPDATEDBY] [int] NULL,
	[UPDATEDDATE] [datetime] NULL,
	[DELETEDBY] [int] NULL,
	[DELETEDDATE] [datetime] NULL,
	[BILLSTATUS] [int] NULL,
	[CUSTOMERNUMBER] [varchar](10) NULL,
	[CUSTOMERNAME] [varchar](100) NULL,
	[DAYCLOSUREID] [int] NULL,
	[SPLDISCPER] [decimal](5, 2) NULL,
	[ISDOORDELIVERY] [bit] NULL,
	[TENDEREDCASH] [decimal](11, 2) NULL,
	[TENDEREDCHANGE] [decimal](11, 2) NULL,
	CUSTOMERGST NVARCHAR(100) NULL
)
GO
CREATE PROC [dbo].[USP_CU_POS_BILL]  
(  
 @Bills POS_BILLTYPE READONLY  
)  
AS  
BEGIN  
 UPDATE B  
 SET  
  B.BILLNUMBER = UB.BILLNUMBER  
  , B.CREATEDBY = UB.CREATEDBY  
  , B.CREATEDDATE = UB.CREATEDDATE  
  , B.UPDATEDBY = UB.UPDATEDBY  
  , B.UPDATEDDATE = UB.UPDATEDDATE  
  , B.DELETEDBY = UB.DELETEDBY  
  , B.DELETEDDATE = UB.DELETEDDATE  
  , B.BILLSTATUS = UB.BILLSTATUS  
  , B.CUSTOMERNUMBER = UB.CUSTOMERNUMBER  
  , B.CUSTOMERNAME = UB.CUSTOMERNAME  
  , B.DAYCLOSUREID = UB.DAYCLOSUREID
  , B.SPLDISCPER = UB.SPLDISCPER
  , B.ISDOORDELIVERY = UB.ISDOORDELIVERY
  , B.TENDEREDCASH = UB.TENDEREDCASH
  , B.TENDEREDCHANGE = UB.TENDEREDCHANGE
  , B.CUSTOMERGST = UB.CUSTOMERGST
 FROM   
  POS_BILL B  
  INNER JOIN @Bills UB ON UB.BILLID = B.BILLID  
 WHERE  
  B.BRANCHCOUNTERID = UB.BRANCHCOUNTERID  
  
 INSERT INTO POS_BILL(BILLID, BRANCHCOUNTERID, BILLNUMBER, CREATEDBY, CREATEDDATE, 
 UPDATEDBY, UPDATEDDATE, DELETEDBY, DELETEDDATE, BILLSTATUS, CUSTOMERNUMBER, CUSTOMERNAME,DAYCLOSUREID
 , SPLDISCPER, ISDOORDELIVERY, TENDEREDCASH, TENDEREDCHANGE, CUSTOMERGST)  
 SELECT BILLID, BRANCHCOUNTERID, BILLNUMBER, CREATEDBY, CREATEDDATE, 
 UPDATEDBY, UPDATEDDATE, DELETEDBY, DELETEDDATE, BILLSTATUS, CUSTOMERNUMBER, CUSTOMERNAME,DAYCLOSUREID
 , SPLDISCPER, ISDOORDELIVERY, TENDEREDCASH, TENDEREDCHANGE, CUSTOMERGST
 FROM @Bills UB  
 WHERE NOT EXISTS  
  (  
   SELECT 1 FROM POS_BILL BINNER WHERE BINNER.BILLID = UB.BILLID AND BINNER.BRANCHCOUNTERID = UB.BRANCHCOUNTERID  
	
  )  
END
GO