
SELECT * FROM POS_BILLDETAIL B WHERE EXISTS (
SELECT 1
FROM POS_BILLDETAIL BINNER
WHERE B.BILLID = BINNER.BILLID AND B.BRANCHCOUNTERID = BINNER.BRANCHCOUNTERID AND B.BILLDETAILID = BINNER.BILLDETAILID
GROUP BY BINNER.BILLID, BINNER.BRANCHCOUNTERID, BINNER.BILLDETAILID
HAVING COUNT(1) > 1)
ORDER BY BILLDETAILID, BILLID, BRANCHCOUNTERID


SELECT COUNT(1) FROM POS_BILLDETAIL


SELECT BD.BILLDETAILID, BD.BILLID, BD.BRANCHCOUNTERID, 
	'DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = ' + CAST(BILLDETAILID AS VARCHAR(10)) + ' AND BILLID = ' + CAST(BILLID AS VARCHAR(10)) + ' AND BRANCHCOUNTERID = '+ CAST(BRANCHCOUNTERID AS VARCHAR(10))
	, COUNT(1)
FROM POS_BILLDETAIL BD 
GROUP BY BD.BILLDETAILID, BD.BILLID, BD.BRANCHCOUNTERID
HAVING COUNT(1) > 1


BEGIN TRAN
commit

SET ROWCOUNT 1

DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3134 AND BILLID = 642 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2784 AND BILLID = 437 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3315 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1544 AND BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2061 AND BILLID = 365 AND BRANCHCOUNTERID = 31
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1550 AND BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3322 AND BILLID = 595 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3309 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3310 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2789 AND BILLID = 437 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3321 AND BILLID = 595 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1543 AND BILLID = 217 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1538 AND BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1938 AND BILLID = 504 AND BRANCHCOUNTERID = 29
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3317 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2782 AND BILLID = 437 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3428 AND BILLID = 1460 AND BRANCHCOUNTERID = 62
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1540 AND BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1547 AND BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3318 AND BILLID = 595 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2781 AND BILLID = 436 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2247 AND BILLID = 471 AND BRANCHCOUNTERID = 66
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2063 AND BILLID = 365 AND BRANCHCOUNTERID = 31
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1552 AND BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2786 AND BILLID = 437 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3306 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3313 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3079 AND BILLID = 625 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3136 AND BILLID = 643 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3312 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1555 AND BILLID = 220 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2785 AND BILLID = 437 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1554 AND BILLID = 219 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3307 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3314 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2787 AND BILLID = 437 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3319 AND BILLID = 595 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3139 AND BILLID = 644 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1542 AND BILLID = 217 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3308 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1553 AND BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3137 AND BILLID = 642 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2788 AND BILLID = 437 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2780 AND BILLID = 436 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3320 AND BILLID = 595 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3311 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3135 AND BILLID = 643 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3138 AND BILLID = 642 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3316 AND BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3429 AND BILLID = 1460 AND BRANCHCOUNTERID = 62
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2783 AND BILLID = 437 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1539 AND BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1548 AND BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1546 AND BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1541 AND BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2248 AND BILLID = 471 AND BRANCHCOUNTERID = 66
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2062 AND BILLID = 365 AND BRANCHCOUNTERID = 31
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2779 AND BILLID = 435 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2791 AND BILLID = 439 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1549 AND BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1443 AND BILLID = 249 AND BRANCHCOUNTERID = 126
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2249 AND BILLID = 472 AND BRANCHCOUNTERID = 66
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3133 AND BILLID = 642 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1551 AND BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2064 AND BILLID = 365 AND BRANCHCOUNTERID = 31
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1939 AND BILLID = 505 AND BRANCHCOUNTERID = 29
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2246 AND BILLID = 471 AND BRANCHCOUNTERID = 66
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 2790 AND BILLID = 438 AND BRANCHCOUNTERID = 56

DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1542 AND BILLID = 217 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1553 AND BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1539 AND BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1541 AND BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1443 AND BILLID = 249 AND BRANCHCOUNTERID = 126
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1939 AND BILLID = 505 AND BRANCHCOUNTERID = 29
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1555 AND BILLID = 220 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1554 AND BILLID = 219 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1543 AND BILLID = 217 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1552 AND BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 3079 AND BILLID = 625 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1938 AND BILLID = 504 AND BRANCHCOUNTERID = 29
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1540 AND BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1544 AND BILLID = 216 AND BRANCHCOUNTERID = 82


DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1541 AND BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1542 AND BILLID = 217 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1543 AND BILLID = 217 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1540 AND BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILLDETAIL WHERE BILLDETAILID = 1544 AND BILLID = 216 AND BRANCHCOUNTERID = 82

SET ROWCOUNT 0