SELECT * FROM POS_BILL B WHERE EXISTS (
SELECT 1
FROM POS_BILL BINNER
WHERE B.BILLID = BINNER.BILLID AND B.BRANCHCOUNTERID = BINNER.BRANCHCOUNTERID
GROUP BY BINNER.BILLID, BINNER.BRANCHCOUNTERID
HAVING COUNT(1) > 1)
 ORDER BY BILLID, BRANCHCOUNTERID

 SELECT COUNT(1) FROM POS_BILL

SELECT BD.BILLID, BD.BRANCHCOUNTERID, 
	'DELETE FROM POS_BILL WHERE BILLID = ' + CAST(BILLID AS VARCHAR(10)) + ' AND BRANCHCOUNTERID = '+ CAST(BRANCHCOUNTERID AS VARCHAR(10))
	, COUNT(1)
FROM POS_BILL BD 
GROUP BY BD.BILLID, BD.BRANCHCOUNTERID
HAVING COUNT(1) > 1
ORDER BY 4


BEGIN TRAN
commit

SET ROWCOUNT 1

DELETE FROM POS_BILL WHERE BILLID = 440 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILL WHERE BILLID = 472 AND BRANCHCOUNTERID = 66
DELETE FROM POS_BILL WHERE BILLID = 365 AND BRANCHCOUNTERID = 31
DELETE FROM POS_BILL WHERE BILLID = 455 AND BRANCHCOUNTERID = 71
DELETE FROM POS_BILL WHERE BILLID = 438 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILL WHERE BILLID = 595 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILL WHERE BILLID = 1461 AND BRANCHCOUNTERID = 62
DELETE FROM POS_BILL WHERE BILLID = 596 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILL WHERE BILLID = 473 AND BRANCHCOUNTERID = 66
DELETE FROM POS_BILL WHERE BILLID = 366 AND BRANCHCOUNTERID = 31
DELETE FROM POS_BILL WHERE BILLID = 435 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILL WHERE BILLID = 364 AND BRANCHCOUNTERID = 31
DELETE FROM POS_BILL WHERE BILLID = 436 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILL WHERE BILLID = 1460 AND BRANCHCOUNTERID = 62
DELETE FROM POS_BILL WHERE BILLID = 234 AND BRANCHCOUNTERID = 23
DELETE FROM POS_BILL WHERE BILLID = 1459 AND BRANCHCOUNTERID = 62
DELETE FROM POS_BILL WHERE BILLID = 735 AND BRANCHCOUNTERID = 10
DELETE FROM POS_BILL WHERE BILLID = 642 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILL WHERE BILLID = 644 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILL WHERE BILLID = 437 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILL WHERE BILLID = 482 AND BRANCHCOUNTERID = 27
DELETE FROM POS_BILL WHERE BILLID = 643 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILL WHERE BILLID = 439 AND BRANCHCOUNTERID = 56
DELETE FROM POS_BILL WHERE BILLID = 594 AND BRANCHCOUNTERID = 69
DELETE FROM POS_BILL WHERE BILLID = 505 AND BRANCHCOUNTERID = 29
DELETE FROM POS_BILL WHERE BILLID = 506 AND BRANCHCOUNTERID = 29
DELETE FROM POS_BILL WHERE BILLID = 504 AND BRANCHCOUNTERID = 29
DELETE FROM POS_BILL WHERE BILLID = 626 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILL WHERE BILLID = 625 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILL WHERE BILLID = 221 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 219 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 250 AND BRANCHCOUNTERID = 126
DELETE FROM POS_BILL WHERE BILLID = 249 AND BRANCHCOUNTERID = 126
DELETE FROM POS_BILL WHERE BILLID = 220 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 217 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 218 AND BRANCHCOUNTERID = 82


DELETE FROM POS_BILL WHERE BILLID = 506 AND BRANCHCOUNTERID = 29
DELETE FROM POS_BILL WHERE BILLID = 249 AND BRANCHCOUNTERID = 126
DELETE FROM POS_BILL WHERE BILLID = 626 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILL WHERE BILLID = 219 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 221 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 505 AND BRANCHCOUNTERID = 29
DELETE FROM POS_BILL WHERE BILLID = 250 AND BRANCHCOUNTERID = 126
DELETE FROM POS_BILL WHERE BILLID = 504 AND BRANCHCOUNTERID = 29
DELETE FROM POS_BILL WHERE BILLID = 625 AND BRANCHCOUNTERID = 25
DELETE FROM POS_BILL WHERE BILLID = 220 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 217 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 216 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 218 AND BRANCHCOUNTERID = 82

DELETE FROM POS_BILL WHERE BILLID = 217 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 218 AND BRANCHCOUNTERID = 82
DELETE FROM POS_BILL WHERE BILLID = 216 AND BRANCHCOUNTERID = 82

SET ROWCOUNT 0
