ALTER TABLE POS_ITEMPRICE
ADD BRANCHID INT NULL
GO
ALTER TABLE POS_ITEMPRICE
ADD PARENTITEMPRICEID INT NULL
GO
DROP PROC [dbo].[POS_USP_CU_ITEMPRICE]
GO
/****** Object:  UserDefinedTableType [dbo].[POS_ITEMPRICETYPE]    Script Date: 16-12-2022 15:06:32 ******/
DROP TYPE [dbo].[POS_ITEMPRICETYPE]
GO

/****** Object:  UserDefinedTableType [dbo].[POS_ITEMPRICETYPE]    Script Date: 16-12-2022 15:06:32 ******/
CREATE TYPE [dbo].[POS_ITEMPRICETYPE] AS TABLE(
	[ITEMPRICEID] [int] NOT NULL,
	[ITEMCODEID] [int] NOT NULL,
	[SALEPRICE] [decimal](7, 2) NULL,
	[MRP] [decimal](7, 2) NULL,
	[GSTID] [int] NOT NULL,
	[CREATEDDATE] [datetime] NULL,
	[UPDATEDATE] [datetime] NULL,
	[DELETEDDATE] [datetime] NULL,
	BRANCHID INT NULL,
	PARENTITEMPRICEID INT NULL
)
GO
CREATE PROC [dbo].[POS_USP_CU_ITEMPRICE]
(
	@ItemPrices POS_ITEMPRICETYPE READONLY
)
AS
BEGIN
	UPDATE IP
	SET
		IP.ITEMCODEID = UIP.ITEMCODEID
		, IP.SALEPRICE = UIP.SALEPRICE
		, IP.MRP = UIP.MRP
		, IP.GSTID = UIP.GSTID
		, IP.CREATEDDATE = UIP.CREATEDDATE
		, IP.UPDATEDATE = UIP.UPDATEDATE
		, IP.DELETEDDATE = UIP.DELETEDDATE
		, IP.BRANCHID = UIP.BRANCHID
		, IP.PARENTITEMPRICEID = UIP.PARENTITEMPRICEID
	FROM
		POS_ITEMPRICE IP
		INNER JOIN @ItemPrices UIP ON UIP.ITEMPRICEID = IP.ITEMPRICEID

	INSERT INTO POS_ITEMPRICE
	(
		ITEMPRICEID
		, ITEMCODEID
		, SALEPRICE
		, MRP
		, GSTID
		, CREATEDDATE
		, UPDATEDATE
		, DELETEDDATE
		, BRANCHID
		, PARENTITEMPRICEID
	)
	SELECT 
		ITEMPRICEID
		, ITEMCODEID
		, SALEPRICE
		, MRP
		, GSTID
		, CREATEDDATE
		, UPDATEDATE
		, DELETEDDATE
		, BRANCHID
		, PARENTITEMPRICEID 
	FROM @ItemPrices UIP
	WHERE NOT EXISTS
		(
			SELECT 1 FROM POS_ITEMPRICE IPINNER WHERE IPINNER.ITEMPRICEID = UIP.ITEMPRICEID
		)
END
GO
ALTER PROC [dbo].[POS_USP_R_ITEMMRPLIST]  
@ItemCodeID INT  
AS  
BEGIN  
	SELECT  
		IP.ITEMPRICEID, 
		IP.MRP, 
		IP.SALEPRICE, 
		GST.GSTID, 
		GST.GSTCODE, 
		GST.SGST, 
		GST.CGST, 
		GST.IGST, 
		GST.CESS  
	FROM
	(SELECT ISNULL(BIP.PARENTITEMPRICEID,IPINNER.ITEMPRICEID) AS ITEMPRICEID FROM POS_ITEMPRICE IPINNER 
		LEFT JOIN POS_ITEMPRICE BIP ON IPINNER.ITEMPRICEID = BIP.PARENTITEMPRICEID) IPOUTER
		INNER JOIN POS_ITEMPRICE IP ON IPOUTER.ITEMPRICEID = IP.ITEMPRICEID
		INNER JOIN POS_GSTDETAIL GST ON GST.GSTID = IP.GSTID  
	WHERE IP.ITEMCODEID = @ItemCodeID  
		AND IP.DELETEDDATE IS NULL
	ORDER BY IP.ITEMPRICEID DESC
END
GO