//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BRANCH()
        {
            this.BRANCHCOUNTERs = new HashSet<BRANCHCOUNTER>();
        }
    
        public int BRANCHID { get; set; }
        public string BRANCHNAME { get; set; }
        public string BRANCHCODE { get; set; }
        public string ADDRESS { get; set; }
        public string PHONENO { get; set; }
        public string LANDLINE { get; set; }
        public string EMAILID { get; set; }
        public Nullable<int> SUPERVISORID { get; set; }
        public Nullable<bool> ISWAREHOUSE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
        public Nullable<int> STATEID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BRANCHCOUNTER> BRANCHCOUNTERs { get; set; }
    }
}
