//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLOUD_STOCKDISPATCHDETAIL
    {
        public int STOCKDISPATCHDETAILID { get; set; }
        public int STOCKDISPATCHID { get; set; }
        public int ITEMPRICEID { get; set; }
        public Nullable<int> TRAYNUMBER { get; set; }
        public int DISPATCHQUANTITY { get; set; }
        public int RECEIVEDQUANTITY { get; set; }
        public Nullable<decimal> WEIGHTINKGS { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<int> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<int> DELETEDBY { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
    }
}
