//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTITYSYNCORDER
    {
        public int ENTITYSYNCORDERID { get; set; }
        public int ENTITYID { get; set; }
        public int SYNCORDER { get; set; }
        public string LOCATIONTYPE { get; set; }
        public string SYNCDIRECTION { get; set; }
    
        public virtual ENTITY ENTITY { get; set; }
    }
}
