//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMPRICE
    {
        public int ITEMPRICEID { get; set; }
        public int ITEMCODEID { get; set; }
        public Nullable<decimal> SALEPRICE { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public int GSTID { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
    }
}
