//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMCODE
    {
        public int ITEMCODEID { get; set; }
        public int ITEMID { get; set; }
        public string ITEMCODE1 { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
        public Nullable<int> FREEITEMCODEID { get; set; }
        public string HSNCODE { get; set; }
        public Nullable<System.DateTime> SYNCDATE { get; set; }
    }
}
