//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NSRetail_CloudEntities : DbContext
    {
        public NSRetail_CloudEntities()
            : base("name=NSRetail_CloudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRANCH> BRANCHes { get; set; }
        public virtual DbSet<BRANCHCOUNTER> BRANCHCOUNTERs { get; set; }
        public virtual DbSet<ENTITY> ENTITies { get; set; }
        public virtual DbSet<ENTITYSYNCORDER> ENTITYSYNCORDERs { get; set; }
        public virtual DbSet<ENTITYSYNCSTATU> ENTITYSYNCSTATUS { get; set; }
        public virtual DbSet<GSTDETAIL> GSTDETAILs { get; set; }
        public virtual DbSet<ITEM> ITEMs { get; set; }
        public virtual DbSet<ITEMCODE> ITEMCODEs { get; set; }
        public virtual DbSet<ITEMPRICE> ITEMPRICEs { get; set; }
        public virtual DbSet<STOCKDISPATCH> STOCKDISPATCHes { get; set; }
        public virtual DbSet<STOCKDISPATCHDETAIL> STOCKDISPATCHDETAILs { get; set; }
        public virtual DbSet<TBLMOP> TBLMOPs { get; set; }
        public virtual DbSet<TBLROLE> TBLROLEs { get; set; }
        public virtual DbSet<TBLUSER> TBLUSERs { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<POS_BILL> POS_BILL { get; set; }
        public virtual DbSet<POS_BILLDETAIL> POS_BILLDETAIL { get; set; }
        public virtual DbSet<CLOUD_STOCKCOUNTING> CLOUD_STOCKCOUNTING { get; set; }
        public virtual DbSet<CLOUD_STOCKCOUNTINGDETAIL> CLOUD_STOCKCOUNTINGDETAIL { get; set; }
        public virtual DbSet<CLOUD_STOCKDISPATCH> CLOUD_STOCKDISPATCH { get; set; }
        public virtual DbSet<CLOUD_STOCKDISPATCHDETAIL> CLOUD_STOCKDISPATCHDETAIL { get; set; }
    
        public virtual int USP_CU_STOCKCOUNTING()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_CU_STOCKCOUNTING");
        }
    
        public virtual int USP_D_STOCKCOUNTING(Nullable<int> sTOCKCOUNTINGID)
        {
            var sTOCKCOUNTINGIDParameter = sTOCKCOUNTINGID.HasValue ?
                new ObjectParameter("STOCKCOUNTINGID", sTOCKCOUNTINGID) :
                new ObjectParameter("STOCKCOUNTINGID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_D_STOCKCOUNTING", sTOCKCOUNTINGIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CLOUD_USP_CU_STOCKCOUNTING(Nullable<int> sTOCKCOUNTINGID, Nullable<int> bRANCHID, Nullable<int> uSERID, Nullable<System.DateTime> cREATEDDATE)
        {
            var sTOCKCOUNTINGIDParameter = sTOCKCOUNTINGID.HasValue ?
                new ObjectParameter("STOCKCOUNTINGID", sTOCKCOUNTINGID) :
                new ObjectParameter("STOCKCOUNTINGID", typeof(int));
    
            var bRANCHIDParameter = bRANCHID.HasValue ?
                new ObjectParameter("BRANCHID", bRANCHID) :
                new ObjectParameter("BRANCHID", typeof(int));
    
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            var cREATEDDATEParameter = cREATEDDATE.HasValue ?
                new ObjectParameter("CREATEDDATE", cREATEDDATE) :
                new ObjectParameter("CREATEDDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CLOUD_USP_CU_STOCKCOUNTING", sTOCKCOUNTINGIDParameter, bRANCHIDParameter, uSERIDParameter, cREATEDDATEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CLOUD_USP_CU_STOCKCOUNTINGDETAIL(Nullable<int> sTOCKCOUNTINGDETAILID, Nullable<int> sTOCKCOUNTINGID, Nullable<int> iTEMPRICEID, Nullable<int> qUANTITY, Nullable<System.DateTime> cREATEDDATE)
        {
            var sTOCKCOUNTINGDETAILIDParameter = sTOCKCOUNTINGDETAILID.HasValue ?
                new ObjectParameter("STOCKCOUNTINGDETAILID", sTOCKCOUNTINGDETAILID) :
                new ObjectParameter("STOCKCOUNTINGDETAILID", typeof(int));
    
            var sTOCKCOUNTINGIDParameter = sTOCKCOUNTINGID.HasValue ?
                new ObjectParameter("STOCKCOUNTINGID", sTOCKCOUNTINGID) :
                new ObjectParameter("STOCKCOUNTINGID", typeof(int));
    
            var iTEMPRICEIDParameter = iTEMPRICEID.HasValue ?
                new ObjectParameter("ITEMPRICEID", iTEMPRICEID) :
                new ObjectParameter("ITEMPRICEID", typeof(int));
    
            var qUANTITYParameter = qUANTITY.HasValue ?
                new ObjectParameter("QUANTITY", qUANTITY) :
                new ObjectParameter("QUANTITY", typeof(int));
    
            var cREATEDDATEParameter = cREATEDDATE.HasValue ?
                new ObjectParameter("CREATEDDATE", cREATEDDATE) :
                new ObjectParameter("CREATEDDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CLOUD_USP_CU_STOCKCOUNTINGDETAIL", sTOCKCOUNTINGDETAILIDParameter, sTOCKCOUNTINGIDParameter, iTEMPRICEIDParameter, qUANTITYParameter, cREATEDDATEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CLOUD_USP_CU_STOCKDISPATCH(Nullable<int> sTOCKDISPATCHID, Nullable<int> fROMBRANCHID, Nullable<int> tOBRANCHID, Nullable<int> cATEGORYID, Nullable<int> uSERID)
        {
            var sTOCKDISPATCHIDParameter = sTOCKDISPATCHID.HasValue ?
                new ObjectParameter("STOCKDISPATCHID", sTOCKDISPATCHID) :
                new ObjectParameter("STOCKDISPATCHID", typeof(int));
    
            var fROMBRANCHIDParameter = fROMBRANCHID.HasValue ?
                new ObjectParameter("FROMBRANCHID", fROMBRANCHID) :
                new ObjectParameter("FROMBRANCHID", typeof(int));
    
            var tOBRANCHIDParameter = tOBRANCHID.HasValue ?
                new ObjectParameter("TOBRANCHID", tOBRANCHID) :
                new ObjectParameter("TOBRANCHID", typeof(int));
    
            var cATEGORYIDParameter = cATEGORYID.HasValue ?
                new ObjectParameter("CATEGORYID", cATEGORYID) :
                new ObjectParameter("CATEGORYID", typeof(int));
    
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CLOUD_USP_CU_STOCKDISPATCH", sTOCKDISPATCHIDParameter, fROMBRANCHIDParameter, tOBRANCHIDParameter, cATEGORYIDParameter, uSERIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CLOUD_USP_CU_STOCKDISPATCHDETAIL(Nullable<int> sTOCKDISPATCHDETAILID, Nullable<int> sTOCKDISPATCHID, Nullable<int> iTEMPRICEID, Nullable<int> tRAYNUMBER, Nullable<int> dISPATCHQUANTITY, Nullable<decimal> wEIGHTINKGS, Nullable<int> uSERID)
        {
            var sTOCKDISPATCHDETAILIDParameter = sTOCKDISPATCHDETAILID.HasValue ?
                new ObjectParameter("STOCKDISPATCHDETAILID", sTOCKDISPATCHDETAILID) :
                new ObjectParameter("STOCKDISPATCHDETAILID", typeof(int));
    
            var sTOCKDISPATCHIDParameter = sTOCKDISPATCHID.HasValue ?
                new ObjectParameter("STOCKDISPATCHID", sTOCKDISPATCHID) :
                new ObjectParameter("STOCKDISPATCHID", typeof(int));
    
            var iTEMPRICEIDParameter = iTEMPRICEID.HasValue ?
                new ObjectParameter("ITEMPRICEID", iTEMPRICEID) :
                new ObjectParameter("ITEMPRICEID", typeof(int));
    
            var tRAYNUMBERParameter = tRAYNUMBER.HasValue ?
                new ObjectParameter("TRAYNUMBER", tRAYNUMBER) :
                new ObjectParameter("TRAYNUMBER", typeof(int));
    
            var dISPATCHQUANTITYParameter = dISPATCHQUANTITY.HasValue ?
                new ObjectParameter("DISPATCHQUANTITY", dISPATCHQUANTITY) :
                new ObjectParameter("DISPATCHQUANTITY", typeof(int));
    
            var wEIGHTINKGSParameter = wEIGHTINKGS.HasValue ?
                new ObjectParameter("WEIGHTINKGS", wEIGHTINKGS) :
                new ObjectParameter("WEIGHTINKGS", typeof(decimal));
    
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CLOUD_USP_CU_STOCKDISPATCHDETAIL", sTOCKDISPATCHDETAILIDParameter, sTOCKDISPATCHIDParameter, iTEMPRICEIDParameter, tRAYNUMBERParameter, dISPATCHQUANTITYParameter, wEIGHTINKGSParameter, uSERIDParameter);
        }
    
        public virtual int CLOUD_USP_D_STOCKCOUNTINGDETAIL(Nullable<int> sTOCKCOUNTINGDETAILID)
        {
            var sTOCKCOUNTINGDETAILIDParameter = sTOCKCOUNTINGDETAILID.HasValue ?
                new ObjectParameter("STOCKCOUNTINGDETAILID", sTOCKCOUNTINGDETAILID) :
                new ObjectParameter("STOCKCOUNTINGDETAILID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CLOUD_USP_D_STOCKCOUNTINGDETAIL", sTOCKCOUNTINGDETAILIDParameter);
        }
    }
}
