//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_BILL
    {
        public int BILLID { get; set; }
        public int BRANCHCOUNTERID { get; set; }
        public string BILLNUMBER { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<int> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<int> DELETEDBY { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
        public Nullable<int> BILLSTATUS { get; set; }
        public string CUSTOMERNUMBER { get; set; }
        public string CUSTOMERNAME { get; set; }
    }
}
