//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_BILLDETAIL
    {
        public int BILLDETAILID { get; set; }
        public int BILLID { get; set; }
        public int BRANCHCOUNTERID { get; set; }
        public int ITEMPRICEID { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<decimal> WEIGHTINKGS { get; set; }
        public Nullable<decimal> BILLEDAMOUNT { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<int> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<int> DELETEDBY { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CESS { get; set; }
        public Nullable<decimal> GSTVALUE { get; set; }
        public Nullable<int> GSTID { get; set; }
        public Nullable<int> SNO { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
    }
}
