//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKDISPATCH
    {
        public int STOCKDISPATCHID { get; set; }
        public int FROMBRANCHID { get; set; }
        public int TOBRANCHID { get; set; }
        public string STATUS { get; set; }
        public string STATUSAPPROVEDBY { get; set; }
        public Nullable<System.DateTime> STATUSAPPROVEDDATE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
        public string DISPATCHNUMBER { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<int> UPDATEDBY { get; set; }
        public Nullable<int> DELETEDBY { get; set; }
    }
}
