//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUSER
    {
        public int USERID { get; set; }
        public int ROLEID { get; set; }
        public Nullable<int> REPORTINGLEADID { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<int> BRANCHID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORDSTRING { get; set; }
        public string FULLNAME { get; set; }
        public string CNUMBER { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ISOTP { get; set; }
        public Nullable<int> GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
        public Nullable<System.DateTime> SYNCDATE { get; set; }
    }
}
