//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSRetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOM
    {
        public int UOMID { get; set; }
        public string DISPLAYVALUE { get; set; }
        public Nullable<int> BASEUOMID { get; set; }
        public decimal MULTIPLIER { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
    }
}
