-- DROP TABLE #Summary
-- DROP TABLE #Ledger


CREATE TABLE #Summary (ITEMID INT,SKUCODE NVARCHAR(50),ITEMNAME NVARCHAR(500), 
DIFF DECIMAL(18,2), LEDGERQUANTITY DECIMAL(18,2), LEDGERWEIGHTINKGS DECIMAL(18,2), ISPROCESSED INT, 
ISOPENITEM BIT, SSQUANTITY DECIMAL(18,2), SSWEIGHTINKGS DECIMAL(18,2))

INSERT INTO #Summary 
select I.ITEMID,I.SKUCODE,I.ITEMNAME, SUM(SSL.OLDQTY - SSL.QUANTITY) AS DIFF, 0 AS LEDGERQUANTITY, 0 AS LEDGERWEIGHTINKGS, 0 AS ISPROCESSED, I.ISOPENITEM, 0 AS SSQUANTITY, 0 AS SSWEIGHTINKGS
from STOCKSUMMARYLOG SSL 
INNER JOIN STOCKSUMMARY SS ON SS.STOCKSUMMARYID = SSL.STOCKSUMMARYID
INNER JOIN ITEMPRICE IP ON SS.ITEMPRICEID = IP.ITEMPRICEID
INNER JOIN ITEMCODE IC ON IP.ITEMCODEID = IC.ITEMCODEID
INNER JOIN ITEM I ON I.ITEMID = IC.ITEMID
WHERE SS.BRANCHID = 55 and (SSL.CREATEDDATE = '2023-03-30 21:12:00.697' OR SSL.CREATEDDATE = '2023-03-31 20:52:48.817') and ssl.ttype = 'BS'
GROUP BY I.ITEMID,I.SKUCODE,I.ITEMNAME, I.ISOPENITEM

CREATE TABLE #Ledger(TRANSACTIONID INT, TRANSACTIONDATE DATE, CREDIT DECIMAL(11,2), DEBIT DECIMAL(11,2), TRANSACTIONTYPE VARCHAR(50), BRANCHNAME VARCHAR(100), RUNNINGBAL DECIMAL(11,2), SKUCODE VARCHAR(10), ITEMNAME VARCHAR(100))

DECLARE @ITEMID INT, @BRANCHID INT = 55, @COUNT INT = 1

DECLARE db_cursor CURSOR FOR 
SELECT ITEMID
FROM #Summary 
WHERE ISPROCESSED = 0
ORDER BY ITEMID


OPEN db_cursor  
FETCH NEXT FROM db_cursor INTO @ITEMID

WHILE @@FETCH_STATUS = 0  
BEGIN  

	--SELECT @COUNT
	SELECT @COUNT = @COUNT + 1

	DELETE FROM #Ledger

	INSERT INTO #Ledger
	EXEC USP_RPT_ITEMLEDGER1 @ItemID = @ITEMID, @FromDate ='2023-01-01', @ToDate = '2023-04-18', @BranchID = @BRANCHID

	UPDATE SS
	SET SS.LEDGERQUANTITY = CASE WHEN SS.ISOPENITEM = 0 THEN CURLED.RUNNINGBAL ELSE 0 END
		, SS.LEDGERWEIGHTINKGS = CASE WHEN SS.ISOPENITEM = 1 THEN CURLED.RUNNINGBAL ELSE 0 END
		, SS.SSQUANTITY = SSINNER.SSQUANTITY
		, SS.SSWEIGHTINKGS = SSINNER.SSWEIGHTINKGS
		, SS.ISPROCESSED = 1
	FROM
		#Summary SS
		INNER JOIN 
		( 
			SELECT TOP(1) * FROM #Ledger ORDER BY TRANSACTIONDATE DESC, TRANSACTIONID DESC
		) CURLED ON SS.ITEMID = @ITEMID
		INNER JOIN
		(
			SELECT IC.ITEMID, SUM(QUANTITY) AS SSQUANTITY, SUM(WEIGHTINKGS) AS SSWEIGHTINKGS FROM STOCKSUMMARY SSINNER 
			INNER JOIN ITEMPRICE IP ON SSINNER.ITEMPRICEID = IP.ITEMPRICEID
			INNER JOIN ITEMCODE IC ON IP.ITEMCODEID = IC.ITEMCODEID
			WHERE SSINNER.BRANCHID = @BRANCHID
			GROUP BY IC.ITEMID
		) SSINNER ON SS.ITEMID = SSINNER.ITEMID

	FETCH NEXT FROM db_cursor INTO @ITEMID
END 

CLOSE db_cursor  
DEALLOCATE db_cursor 



select
ITEMID,SKUCODE,ITEMNAME, DIFF AS SSLDIFF, LEDGERQUANTITY, LEDGERWEIGHTINKGS, ISPROCESSED, ISOPENITEM, SSQUANTITY, SSWEIGHTINKGS,
CASE WHEN ISOPENITEM = 0 THEN LEDGERQUANTITY - SSQUANTITY ELSE LEDGERWEIGHTINKGS - SSWEIGHTINKGS END AS SSDIFF,
CASE WHEN DIFF = CASE WHEN ISOPENITEM = 0 THEN LEDGERQUANTITY - SSQUANTITY ELSE LEDGERWEIGHTINKGS - SSWEIGHTINKGS END THEN 'TRUE' ELSE 'FALSE' END AS MATCHED
from #Summary WHERE ISPROCESSED = 1
