IF NOT EXISTS (SELECT 1 FROM SYS.all_columns WHERE [OBJECT_ID] = OBJECT_ID('POS_BILL') AND [NAME] = 'SPLDISCPER')
BEGIN
	EXEC ('ALTER TABLE POS_BILL ADD SPLDISCPER DECIMAL(5, 2)')
END

IF NOT EXISTS (SELECT 1 FROM SYS.all_columns WHERE [OBJECT_ID] = OBJECT_ID('POS_BILL') AND [NAME] = 'ISDOORDELIVERY')
BEGIN
	EXEC ('ALTER TABLE POS_BILL ADD ISDOORDELIVERY BIT')
END

IF NOT EXISTS (SELECT 1 FROM SYS.all_columns WHERE [OBJECT_ID] = OBJECT_ID('POS_BILL') AND [NAME] = 'TENDEREDCASH')
BEGIN
	EXEC ('ALTER TABLE POS_BILL ADD TENDEREDCASH DECIMAL(11, 2)')
END

IF NOT EXISTS (SELECT 1 FROM SYS.all_columns WHERE [OBJECT_ID] = OBJECT_ID('POS_BILL') AND [NAME] = 'TENDEREDCHANGE')
BEGIN
	EXEC ('ALTER TABLE POS_BILL ADD TENDEREDCHANGE DECIMAL(11, 2)')
END

GO


/****** Object:  StoredProcedure [dbo].[USP_CU_POS_BILL]    Script Date: 14-04-2022 08:05:45 ******/
DROP PROCEDURE [dbo].[USP_CU_POS_BILL]
GO

/****** Object:  UserDefinedTableType [dbo].[POS_BILLTYPE]    Script Date: 14-04-2022 08:06:05 ******/
DROP TYPE [dbo].[POS_BILLTYPE]
GO

/****** Object:  UserDefinedTableType [dbo].[POS_BILLTYPE]    Script Date: 14-04-2022 08:06:05 ******/
CREATE TYPE [dbo].[POS_BILLTYPE] AS TABLE(
	[BILLID] [int] NOT NULL,
	[BRANCHCOUNTERID] [int] NOT NULL,
	[BILLNUMBER] [varchar](30) NULL,
	[CREATEDBY] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[UPDATEDBY] [int] NULL,
	[UPDATEDDATE] [datetime] NULL,
	[DELETEDBY] [int] NULL,
	[DELETEDDATE] [datetime] NULL,
	[BILLSTATUS] [int] NULL,
	[CUSTOMERNUMBER] [varchar](10) NULL,
	[CUSTOMERNAME] [varchar](100) NULL,
	[DAYCLOSUREID] [int] NULL,
	SPLDISCPER DECIMAL(5, 2),
	ISDOORDELIVERY BIT,
	TENDEREDCASH DECIMAL(11, 2),
	TENDEREDCHANGE DECIMAL(11, 2)
)
GO


CREATE PROC [dbo].[USP_CU_POS_BILL]  
(  
 @Bills POS_BILLTYPE READONLY  
)  
AS  
BEGIN  
 UPDATE B  
 SET  
  B.BILLNUMBER = UB.BILLNUMBER  
  , B.CREATEDBY = UB.CREATEDBY  
  , B.CREATEDDATE = UB.CREATEDDATE  
  , B.UPDATEDBY = UB.UPDATEDBY  
  , B.UPDATEDDATE = UB.UPDATEDDATE  
  , B.DELETEDBY = UB.DELETEDBY  
  , B.DELETEDDATE = UB.DELETEDDATE  
  , B.BILLSTATUS = UB.BILLSTATUS  
  , B.CUSTOMERNUMBER = UB.CUSTOMERNUMBER  
  , B.CUSTOMERNAME = UB.CUSTOMERNAME  
  , B.DAYCLOSUREID = UB.DAYCLOSUREID
  , B.SPLDISCPER = UB.SPLDISCPER
  , B.ISDOORDELIVERY = UB.ISDOORDELIVERY
  , B.TENDEREDCASH = UB.TENDEREDCASH
  , B.TENDEREDCHANGE = UB.TENDEREDCHANGE
 FROM   
  POS_BILL B  
  INNER JOIN @Bills UB ON UB.BILLID = B.BILLID  
 WHERE  
  B.BRANCHCOUNTERID = UB.BRANCHCOUNTERID  
  
 INSERT INTO POS_BILL(BILLID, BRANCHCOUNTERID, BILLNUMBER, CREATEDBY, CREATEDDATE, 
 UPDATEDBY, UPDATEDDATE, DELETEDBY, DELETEDDATE, BILLSTATUS, CUSTOMERNUMBER, CUSTOMERNAME,DAYCLOSUREID
 , SPLDISCPER, ISDOORDELIVERY, TENDEREDCASH, TENDEREDCHANGE)  
 SELECT BILLID, BRANCHCOUNTERID, BILLNUMBER, CREATEDBY, CREATEDDATE, 
 UPDATEDBY, UPDATEDDATE, DELETEDBY, DELETEDDATE, BILLSTATUS, CUSTOMERNUMBER, CUSTOMERNAME,DAYCLOSUREID
 , SPLDISCPER, ISDOORDELIVERY, TENDEREDCASH, TENDEREDCHANGE
 FROM @Bills UB  
 WHERE NOT EXISTS  
  (  
   SELECT 1 FROM POS_BILL BINNER WHERE BINNER.BILLID = UB.BILLID AND BINNER.BRANCHCOUNTERID = UB.BRANCHCOUNTERID  
	
  )  
END
GO