select SS.*,
LEDGERQUANTITY - SSQUANTITY AS SSDIFF,
CASE WHEN LEDGERQUANTITY = SSQUANTITY THEN 'TRUE' ELSE 'FALSE' END AS MATCHED,
B.BRANCHid, B.BRANCHNAME
from SUMMARYTEMP SS INNER JOIN BRANCH B ON SS.BRANCHID = B.BRANCHID
WHERE ISPROCESSED = 1