select CAST(SSL.CREATEDDATE AS DATE) AS CREATEDDATE, SUM(SSL.OLDQTY - SSL.QUANTITY) AS DIFF, SSL.TTYPE from STOCKSUMMARYLOG SSL 
INNER JOIN STOCKSUMMARY SS ON SS.STOCKSUMMARYID = SSL.STOCKSUMMARYID
INNER JOIN ITEMPRICE IP ON SS.ITEMPRICEID = IP.ITEMPRICEID AND IP.ITEMCODEID = 25069
WHERE SS.BRANCHID = 48 and SSL.CREATEDDATE > '2023-03-14 15:00:00' and ssl.ttype = 'BS'
GROUP BY CAST(SSL.CREATEDDATE AS DATE), SSL.TTYPE
ORDER BY CAST(SSL.CREATEDDATE AS DATE)

select SUM(SSL.OLDQTY - SSL.QUANTITY) AS DIFF from STOCKSUMMARYLOG SSL 
INNER JOIN STOCKSUMMARY SS ON SS.STOCKSUMMARYID = SSL.STOCKSUMMARYID
INNER JOIN ITEMPRICE IP ON SS.ITEMPRICEID = IP.ITEMPRICEID AND IP.ITEMCODEID = 25069
WHERE SS.BRANCHID = 48 and SSL.CREATEDDATE > '2023-03-14 15:00:00' and ssl.ttype = 'BS'


select SSL.*, SSL.OLDQTY - SSL.QUANTITY AS DIFF from STOCKSUMMARYLOG SSL 
INNER JOIN STOCKSUMMARY SS ON SS.STOCKSUMMARYID = SSL.STOCKSUMMARYID
INNER JOIN ITEMPRICE IP ON SS.ITEMPRICEID = IP.ITEMPRICEID AND IP.ITEMCODEID = 25069
WHERE SS.BRANCHID = 48 and SSL.CREATEDDATE > '2023-03-14 15:00:00' and ssl.ttype = 'BS'
ORDER BY CAST(SSL.CREATEDDATE AS DATE)