-- DROP TABLE #Ledger

IF NOT EXISTS(SELECT 1 FROM SUMMARYTEMP)
BEGIN
	INSERT INTO SUMMARYTEMP
	select I.ITEMID,I.SKUCODE,I.ITEMNAME, 
	CASE WHEN ISNULL(I.ISOPENITEM,0) = 0 THEN SUM(SS.QUANTITY) ELSE SUM(SS.WEIGHTINKGS) END 
	, 0 AS LEDGERQUANTITY, 0 AS LEDGERWEIGHTINKGS, 0 AS ISPROCESSED, I.ISOPENITEM, 0 AS SSQUANTITY, 0 AS SSWEIGHTINKGS, SS.BRANCHID
	FROM STOCKSUMMARY SS
	INNER JOIN ITEMPRICE IP ON SS.ITEMPRICEID = IP.ITEMPRICEID
	INNER JOIN ITEMCODE IC ON IP.ITEMCODEID = IC.ITEMCODEID
	INNER JOIN ITEM I ON I.ITEMID = IC.ITEMID
	GROUP BY I.ITEMID,I.SKUCODE,I.ITEMNAME, I.ISOPENITEM, SS.BRANCHID
END

CREATE TABLE #Ledger(TRANSACTIONID INT, TRANSACTIONDATE DATE, CREDIT DECIMAL(11,2), DEBIT DECIMAL(11,2), TRANSACTIONTYPE VARCHAR(50), BRANCHNAME VARCHAR(100), RUNNINGBAL DECIMAL(11,2), SKUCODE VARCHAR(10), ITEMNAME VARCHAR(100))

DECLARE @ITEMID INT, @BRANCHID INT, @COUNT INT = 1

DECLARE db_cursor CURSOR FOR 
SELECT ITEMID, BRANCHID
FROM SUMMARYTEMP 
WHERE ISPROCESSED = 0
ORDER BY ITEMID


OPEN db_cursor  
FETCH NEXT FROM db_cursor INTO @ITEMID, @BRANCHID

WHILE @@FETCH_STATUS = 0  
BEGIN  

	--SELECT @COUNT
	SELECT @COUNT = @COUNT + 1

	DELETE FROM #Ledger

	INSERT INTO #Ledger
	EXEC USP_RPT_ITEMLEDGER1 @ItemID = @ITEMID, @FromDate ='2023-12-01', @ToDate = '2023-04-21', @BranchID = @BRANCHID

	UPDATE SS
	SET SS.LEDGERQUANTITY = CASE WHEN SS.ISOPENITEM = 0 THEN CURLED.RUNNINGBAL ELSE 0 END
		, SS.LEDGERWEIGHTINKGS = CASE WHEN SS.ISOPENITEM = 1 THEN CURLED.RUNNINGBAL ELSE 0 END
		, SS.SSQUANTITY = SSINNER.SSQUANTITY
		, SS.SSWEIGHTINKGS = SSINNER.SSWEIGHTINKGS
		, SS.ISPROCESSED = 1
	FROM
		SUMMARYTEMP SS
		INNER JOIN 
		( 
			SELECT TOP(1) * FROM #Ledger ORDER BY TRANSACTIONDATE DESC, TRANSACTIONID DESC
		) CURLED ON SS.ITEMID = @ITEMID
		INNER JOIN
		(
			SELECT IC.ITEMID, SUM(QUANTITY) AS SSQUANTITY, SUM(WEIGHTINKGS) AS SSWEIGHTINKGS FROM STOCKSUMMARY SSINNER 
			INNER JOIN ITEMPRICE IP ON SSINNER.ITEMPRICEID = IP.ITEMPRICEID
			INNER JOIN ITEMCODE IC ON IP.ITEMCODEID = IC.ITEMCODEID
			WHERE SSINNER.BRANCHID = @BRANCHID
			GROUP BY IC.ITEMID
		) SSINNER ON SS.ITEMID = SSINNER.ITEMID

	FETCH NEXT FROM db_cursor INTO @ITEMID, @BRANCHID
END 

CLOSE db_cursor  
DEALLOCATE db_cursor 

select
ITEMID,SKUCODE,ITEMNAME, LEDGERQUANTITY, LEDGERWEIGHTINKGS, ISPROCESSED, ISOPENITEM, SSQUANTITY, SSWEIGHTINKGS,
CASE WHEN ISOPENITEM = 0 THEN LEDGERQUANTITY - SSQUANTITY ELSE LEDGERWEIGHTINKGS - SSWEIGHTINKGS END AS SSDIFF,
CASE WHEN LEDGERQUANTITY = SSQUANTITY THEN 'TRUE' ELSE 'FALSE' END AS MATCHED,
BRANCHid
from SUMMARYTEMP WHERE ISPROCESSED = 1
